#!/bin/bash

# This is a normal file because windows is stupid.

go get -d -t -v ./...
go build -v ./...
go test -v ./...
go test -a -tags bounds -v ./...
go test -a -tags noasm -v ./...
go test -a -tags appengine -v ./...
