sudo: false

language: go

# Versions of go that are explicitly supported by gonum.
go:
 - 1.5.4
 - 1.6.3
 - 1.7.3

# Required for coverage, testing and generate.
before_install:
 - go get golang.org/x/tools/cmd/cover
 - go get golang.org/x/tools/cmd/goimports
 - go get github.com/mattn/goveralls
 - go get github.com/klauspost/asmfmt/cmd/asmfmt

# Get deps, build, test, and ensure the code is gofmt'ed.
# If we are building as gonum, then we have access to the coveralls api key, so we can run coverage as well.
script:
 - go get -d -t -v ./...
 - go build -v -x ./...
 - go test -v -x -a ./...
 - go test -v -x -a -tags noasm ./...
 - go test -v -x -a -tags appengine ./...
 - test -z "$(gofmt -d .)"
 - diff <(asmfmt -d .) <("")
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash ./.travis/test-coverage.sh; fi
