name: Staticcheck
on:
  pull_request:
    branches: [master]

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    env:
        GO111MODULE: on
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        min-go-version: 1.20.14
