name: Staticcheck
on:
  pull_request:
    branches: [master]

jobs:
  ci:
    name: lint
    runs-on: ubuntu-latest
    env:
        GO111MODULE: on
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.2.0
      with:
        version: "2022.1"
