name: Staticcheck
on:
  pull_request:
    branches: [master]

jobs:
  ci:
    name: lint
    strategy:
      matrix:
        go: ["1.20.x"]
    runs-on: ubuntu-latest
    env:
        GO111MODULE: on
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: WillAbides/setup-go-faster@v1.7.0
      with:
        go-version: ${{ matrix.go }}
    - uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"
        install-go: false
        cache-key: ${{ matrix.go }}
